### ISSUE TITLE
HTMLファイルのエクスポート機能が欲しい

### ISSUE THREAD

**Issue by baronTommy** [Himenon/code-dependency#32]
はじめまして

視認性が良く気にっています 👀
機能要望があります 検討お願いします

---

HTMLファイルのエクスポート機能が欲しい

たぶん下記コマンド だと思います。
https://github.com/Himenon/code-dependency/blob/master/packages/cli/package.json#L30

こんな風に使いたいです

```bash
yarn export --path some/out
```

**Comment by Himenon** [comment]
issueありがとうございます。

HTMLのexport機能ではありませんが、内部で利用しているライブラリはSVG、PNGなどにexportする機能を持っているので、こちらを利用するのが手っ取り早いかもしれません。

* https://github.com/sverweij/dependency-cruiser#show-stuff-to-your-grandma

事足りないようでしたらもう少し詳しく希望する機能の説明をお願いします。

**Comment by baronTommy** [comment]
レスありがとうございます 

HTMLファイルのエクスポート -> `netlify` へデプロイ のような利用を想定しています。
`storybooks`の `build` のように使いたいです

**Comment by Himenon** [comment]
なるほど。生成する容量が大きくなってしまいますが。試してみましょう。

**Comment by Himenon** [comment]
@baronTommy 

`--export-static`というoptionを追加してみました。ご確認ください。

* https://github.com/Himenon/code-dependency/tree/master/packages/cli

DEMO

* https://himenon.github.io/code-dependency/project/src/index.html

**Comment by baronTommy** [comment]
@Himenon 

対応ありがとうございます ⛑


動作しないような気がしています... 下記に検証したコードをのせています
https://github.com/baronTommy/onigiri

create react + code-dependency だけの最小構成です
- code-dependency --source ./src
- code-dependency --source ./src --export-static

🐤

**Comment by Himenon** [comment]
@baronTommy 

`--export-static`は出力先のディレクトリを引数に取ります。以下のようにしたら動作することを確認しました。

```bash
code-dependency --source ./src --export-static ./output
```

また、`--export-static`によって生成されるディレクトリ構成がドキュメントに書いたようになっています。

https://github.com/Himenon/code-dependency/tree/master/packages/cli#code-dependencycli

![image](https://user-images.githubusercontent.com/6715229/73944316-b9f29a80-4935-11ea-8925-4715fe4be631.png)

**Comment by baronTommy** [comment]
確認不足でした 申し訳有りません

期待通りの動作です

**Comment by baronTommy** [comment]
感動したので あらためて再度お礼

モノレポの勉強してまして、全体像みたいなと思ってました
本当に最高です 😇

![2020-02-08 at 19 09](https://user-images.githubusercontent.com/16768208/74083374-b6caec00-4aa6-11ea-859a-bbaac3740692.png)

**Comment by Himenon** [comment]
理解の手助けとなれて光栄です。紹介の記事をちょうど書きましたので、ぜひご覧ください。

https://qiita.com/himenoglyph/items/f28a9905e3b30e6cb213
